export const BALANCE = {
  MAX_TURNS: 30,

  // Win thresholds
  BRB_ENGINEERING_THRESHOLD: 70,
  BRB_ACCESS_THRESHOLD: 60,
  BRB_LEGITIMACY_THRESHOLD: 40,
  BRB_STABILITY_THRESHOLD: 50,

  // Loss thresholds
  MAX_STRESS: 100,
  MAX_PANIC: 100,
  MIN_MONEY: -1000,
  CPU_WIN_THRESHOLD: 100,

  // Resource clamp ranges
  MIN_INFLUENCE: 0,
  MIN_INTEL: 0,
  MIN_TRUST: 0,
  MAX_STRESS_CAP: 100,
  MAX_PANIC_CAP: 100,

  // BRB track clamps
  MAX_BRB_TRACK: 100,
  MIN_BRB_TRACK: 0,

  // Advisor stat ranges
  MIN_LOYALTY: -100,
  MAX_LOYALTY: 100,
  MIN_ALIGNMENT: -100,
  MAX_ALIGNMENT: 100,
  MIN_LEVERAGE: 0,
  MAX_LEVERAGE: 100,

  // Alignment decay settings
  DECAY_EVERY_N_TURNS: 5,
  ALIGNMENT_DECAY_TOWARD_ZERO: 5,
  LOYALTY_ABOVE_CEILING_DECAY: 3,

  // CPU scaling
  CPU_PRESSURE_INCREMENT_EVERY: 8,

  // Ending quality thresholds
  CONTROLLED_STABILITY: 75,
  CONTROLLED_PANIC_MAX: 50,
  DIRTY_VICTORY_MIN_STABILITY: 50,
  COUP_BUTTON_LEGITIMACY_MAX: 30,
  PANIC_MANDATE_PANIC_MIN: 80,
  STALEMATE_PLAYER_MIN_PROGRESS: 180,
  STALEMATE_CPU_MAX: 70,
  HIGH_PANIC_THRESHOLD: 65,

  // Event frequency
  EVENT_CHANCE_PER_TURN: 0.4,
} as const;
