import type {
  AdvisorDefinition,
  ArchetypeDefinition,
  CorporationMove,
  Ending,
  EndingId,
  ResourcePool,
  RouteId,
  SituationCard,
  TrackKey,
} from "./types";

export const BASE_RESOURCES: ResourcePool = {
  money: 48,
  influence: 42,
  intelligence: 38,
  trust: 46,
  capacity: 44,
};

export const ADVISORS: Record<AdvisorDefinition["id"], AdvisorDefinition> = {
  analyst: {
    id: "analyst",
    name: "The Analyst",
    specialty: "Forecasts and Corporation intelligence",
    agenda: ["counter", "deposit"],
    crisisSpecialty: "infiltrating",
    baseCompetence: 82,
    loyaltyCeiling: 76,
    breakingPoint: 24,
    bias: "Prefers precise plans even when delay is dangerous.",
  },
  fixer: {
    id: "fixer",
    name: "The Fixer",
    specialty: "Crisis control and political deals",
    agenda: ["advisor", "faction", "counter"],
    crisisSpecialty: "buying_influence",
    baseCompetence: 76,
    loyaltyCeiling: 70,
    breakingPoint: 20,
    bias: "Treats personal leverage as the price of effective action.",
  },
  steward: {
    id: "steward",
    name: "The Steward",
    specialty: "Public trust and institutional stability",
    agenda: ["card", "institutions", "deposit"],
    crisisSpecialty: "discrediting",
    baseCompetence: 70,
    loyaltyCeiling: 84,
    breakingPoint: 30,
    bias: "Rejects shortcuts that weaken legitimacy.",
  },
};

export const ARCHETYPES: Record<ArchetypeDefinition["id"], ArchetypeDefinition> = {
  technocrat: {
    id: "technocrat",
    name: "Technocrat",
    description: "Precise forecasts and technical execution, with a weaker public connection.",
    resourceChanges: { intelligence: 10, capacity: 8, trust: -8 },
    trackChanges: { engineering: 5 },
    advisorChanges: { analyst: { loyalty: 8, alignment: 8 } },
    favoredCardType: "corporation",
    liability: "Opaque choices cost 3 additional Trust.",
    endingVariationTitle: "Perfect Machine, Empty State",
  },
  populist: {
    id: "populist",
    name: "Populist",
    description: "Strong public energy with dangerous consequences when that public is betrayed.",
    resourceChanges: { trust: 12, influence: 6, intelligence: -6 },
    trackChanges: { legitimacy: 5 },
    advisorChanges: { steward: { loyalty: 6 }, fixer: { leverage: 5 } },
    favoredCardType: "crisis",
    liability: "Public betrayal choices add 5 additional Panic.",
    endingVariationTitle: "The Crowd Presses the Button",
  },
  operator: {
    id: "operator",
    name: "Operator",
    description: "Efficient crisis control bought with rapidly rising advisor leverage.",
    resourceChanges: { money: 8, influence: 8, trust: -5 },
    trackChanges: { access: 5 },
    advisorChanges: { fixer: { competence: 8, leverage: 8 } },
    favoredCardType: "advisor",
    liability: "Consultations create twice the normal leverage.",
    endingVariationTitle: "Government by Command",
  },
};

export const DEPOSIT_COSTS: Record<TrackKey, ResourcePool> = {
  engineering: { money: 10, influence: 0, intelligence: 3, trust: 0, capacity: 7 },
  access: { money: 0, influence: 9, intelligence: 7, trust: 0, capacity: 3 },
  legitimacy: { money: 0, influence: 6, intelligence: 0, trust: 10, capacity: 2 },
  stability: { money: 6, influence: 0, intelligence: 0, trust: 6, capacity: 6 },
};

export const CORPORATION_MOVES: Record<CorporationMove["id"], CorporationMove> = {
  expanding: {
    id: "expanding",
    name: "Expand",
    description: "The Corporation advances its project while the player is distracted.",
    effects: { corporationProgress: 6, corporationThreat: 2 },
  },
  infiltrating: {
    id: "infiltrating",
    name: "Infiltrate",
    description: "Insiders compromise technical capacity and intelligence.",
    effects: {
      resources: { capacity: -4, intelligence: -3 },
      corporationProgress: 4,
      corporationThreat: 5,
    },
  },
  discrediting: {
    id: "discrediting",
    name: "Discredit",
    description: "A public campaign attacks the project's legitimacy.",
    effects: {
      resources: { trust: -6 },
      pressures: { panic: 5 },
      corporationProgress: 3,
      corporationThreat: 3,
    },
  },
  buying_influence: {
    id: "buying_influence",
    name: "Buy Influence",
    description: "The Corporation buys allies and makes the coalition expensive to hold.",
    effects: {
      resources: { influence: -5 },
      corporationProgress: 5,
      corporationThreat: 3,
      advisors: { fixer: { leverage: 2 } },
    },
  },
};

export const ENDING_COPY: Record<
  EndingId,
  Omit<Ending, "reason" | "variationId" | "variationTitle">
> = {
  civic_legacy: {
    id: "civic_legacy",
    title: "A Republic Still Standing",
    description: "The BRB activates under public and institutional control.",
    victory: true,
  },
  compromised_activation: {
    id: "compromised_activation",
    title: "The Necessary Regime",
    description: "The BRB activates, but the shortcuts used to finish it become permanent rule.",
    victory: true,
  },
  corporate_capture: {
    id: "corporate_capture",
    title: "Terms and Conditions",
    description: "The Corporation controls the project, its operators, or the state around it.",
    victory: false,
  },
  state_collapse: {
    id: "state_collapse",
    title: "The Project Outlived the State",
    description: "The campaign ends before the player can safely activate the BRB.",
    victory: false,
  },
};

const COMMON = { rarity: "common" as const, cooldownTurns: 4, maxPerRun: 2 };
const RARE = { rarity: "rare" as const, cooldownTurns: 99, maxPerRun: 1 };

export const SITUATION_CARDS: SituationCard[] = [
  {
    ...COMMON,
    id: "budget_shortfall",
    title: "The Missing Appropriation",
    description: "A promised funding block disappears during committee review.",
    type: "crisis",
    weight: 8,
    followUps: [],
    choices: [
      {
        id: "cut",
        label: "Cut public programs",
        effects: { resources: { money: 12, trust: -8 }, pressures: { stress: 2 } },
        echoHint: "The public ledger will remember what was cut.",
        echoes: [{ type: "ending", hint: "Austerity entered the historical record.", contributor: "austerity_first" }],
        tags: ["public_betrayal"],
      },
      {
        id: "delay",
        label: "Accept the delay",
        effects: { resources: { capacity: -5 }, pressures: { stress: 5 } },
        echoHint: "The project schedule is now politically exposed.",
        echoes: [{ type: "system", hint: "Delay became part of the project doctrine.", modifier: "accepted_delay" }],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { money: -7 }, pressures: { stress: 5 } },
      echoHint: "Unanswered appropriations questions are spreading.",
      echoes: [{ type: "ending", hint: "Neglect entered the record.", contributor: "fiscal_neglect" }],
    },
  },
  {
    ...COMMON,
    id: "whistleblower",
    title: "The Steward's Red Folder",
    description: "The Steward brings evidence that an employee may expose the procurement trail.",
    type: "advisor",
    weight: 7,
    followUps: [],
    choices: [
      {
        id: "protect",
        label: "Protect the whistleblower",
        effects: { resources: { trust: 9, intelligence: -5 }, institutions: 5 },
        echoHint: "The Steward will remember that institutions came first.",
        echoes: [{ type: "relationship", hint: "The Steward remembers your restraint.", advisorId: "steward", memory: "protected_whistleblower" }],
      },
      {
        id: "contain",
        label: "Let the Fixer contain it",
        effects: { resources: { influence: -5 }, advisors: { fixer: { leverage: 5, alignment: 5 } }, institutions: -4 },
        echoHint: "The Fixer now owns part of this secret.",
        echoes: [{ type: "relationship", hint: "The Fixer remembers the secret you shared.", advisorId: "fixer", memory: "contained_whistleblower" }],
        tags: ["opaque"],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { trust: -9 }, pressures: { panic: 5 } },
      echoHint: "Silence has been interpreted as guilt.",
      echoes: [{ type: "ending", hint: "Institutional neglect entered the record.", contributor: "ignored_whistleblower" }],
    },
  },
  {
    ...COMMON,
    id: "contractor_strike",
    title: "Contractors Walk Out",
    description: "The people who understand the prototype demand safer conditions.",
    type: "crisis",
    weight: 7,
    requirements: { minTrack: { engineering: 18 } },
    followUps: [],
    choices: [
      {
        id: "pay",
        label: "Meet their demands",
        effects: { resources: { money: -9, capacity: 5 }, institutions: 2 },
        echoHint: "Organized labor sees that pressure can work.",
        echoes: [{ type: "ending", hint: "Labor accommodation entered the record.", contributor: "labor_accommodation" }],
      },
      {
        id: "replace",
        label: "Replace the organizers",
        effects: { resources: { capacity: -8, influence: -4 }, pressures: { stress: 5 } },
        echoHint: "Replacement crews will not forget how they arrived.",
        echoes: [{ type: "system", hint: "Contractor fear now shapes Engineering.", modifier: "replacement_contractors" }],
        tags: ["public_betrayal"],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { capacity: -10 }, pressures: { stress: 5 } },
      echoHint: "The walkout is becoming a movement.",
      echoes: [{ type: "ending", hint: "Labor neglect entered the record.", contributor: "ignored_labor" }],
    },
  },
  {
    ...COMMON,
    id: "public_hearing",
    title: "The Corporation Forces a Hearing",
    description: "Corporation allies turn routine oversight into national television.",
    type: "corporation",
    weight: 7,
    requirements: { minTurn: 3 },
    followUps: [],
    choices: [
      {
        id: "transparent",
        label: "Answer in public",
        effects: { resources: { trust: 10, intelligence: -6 }, corporationThreat: 3 },
        echoHint: "Public testimony has narrowed your future denials.",
        echoes: [{ type: "ending", hint: "Transparency entered the record.", contributor: "public_testimony" }],
      },
      {
        id: "closed",
        label: "Move to closed session",
        effects: { resources: { influence: -6, trust: -4 }, pressures: { panic: -2 } },
        echoHint: "A classified version of the hearing now exists.",
        echoes: [{ type: "system", hint: "Secrecy became standard procedure.", modifier: "closed_oversight" }],
        tags: ["opaque"],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { trust: -7 }, institutions: -3 },
      echoHint: "The Corporation is writing the public account for you.",
      echoes: [{ type: "ending", hint: "Corporate narrative control entered the record.", contributor: "corporate_narrative" }],
    },
  },
  {
    ...RARE,
    id: "insider_offer",
    title: "The Analyst's Defector",
    description: "The Analyst presents a Corporation executive offering plans for immunity.",
    type: "advisor",
    weight: 5,
    requirements: { minTurn: 4 },
    followUps: [],
    choices: [
      {
        id: "deal",
        label: "Make the deal",
        effects: { resources: { intelligence: 12, trust: -4 }, corporationThreat: -5, institutions: -2 },
        echoHint: "The defector expects protection after activation.",
        echoes: [{ type: "relationship", hint: "The Analyst remembers the immunity deal.", advisorId: "analyst", memory: "protected_defector" }],
        tags: ["opaque"],
      },
      {
        id: "sting",
        label: "Turn the offer into a sting",
        effects: { resources: { intelligence: -5 }, corporationProgress: -8, corporationThreat: 4 },
        echoHint: "The Corporation now suspects its internal channels.",
        echoes: [{ type: "ending", hint: "Active resistance entered the record.", contributor: "corporate_sting" }],
      },
    ],
    ignoredOutcome: {
      effects: { corporationProgress: 5 },
      echoHint: "The defector returned to the Corporation with your silence.",
      echoes: [{ type: "ending", hint: "A missed defection entered the record.", contributor: "missed_defector" }],
    },
  },
  {
    ...RARE,
    id: "intelligence_leak",
    title: "The Briefing Was Forwarded",
    description: "Sensitive projections appear in a Corporation operations room.",
    type: "corporation",
    weight: 5,
    requirements: { minTrack: { access: 18 } },
    followUps: [],
    choices: [
      {
        id: "audit",
        label: "Audit the inner circle",
        effects: { resources: { intelligence: -5 }, advisors: { analyst: { loyalty: -4 }, fixer: { loyalty: -4 }, steward: { loyalty: -4 } }, corporationThreat: -3 },
        echoHint: "Every advisor now knows they were investigated.",
        echoes: [{ type: "relationship", hint: "The cabinet remembers the loyalty audit.", advisorId: "analyst", memory: "subjected_to_loyalty_audit" }],
      },
      {
        id: "false",
        label: "Feed them a false plan",
        effects: { resources: { intelligence: -8 }, corporationProgress: -6, pressures: { stress: 3 } },
        echoHint: "A false project timeline is moving through the Corporation.",
        echoes: [{ type: "system", hint: "Deception changed future Corporation forecasts.", modifier: "false_plan_in_circulation" }],
        tags: ["opaque"],
      },
    ],
    ignoredOutcome: {
      effects: { corporationProgress: 7, corporationThreat: 4 },
      echoHint: "The Corporation is treating the leak as confirmed intelligence.",
      echoes: [{ type: "ending", hint: "Compromised intelligence entered the record.", contributor: "confirmed_leak" }],
    },
  },
  {
    ...COMMON,
    id: "regional_blackout",
    title: "A Regional Blackout",
    description: "A grid failure tests whether the state supports the project or its people first.",
    type: "crisis",
    weight: 7,
    requirements: { minTurn: 5 },
    followUps: [],
    choices: [
      {
        id: "public",
        label: "Restore public service first",
        effects: { resources: { capacity: -9, trust: 8 }, tracks: { engineering: -3 } },
        echoHint: "The public saw which grid came first.",
        echoes: [{ type: "ending", hint: "Public service entered the record.", contributor: "public_grid_first" }],
      },
      {
        id: "project",
        label: "Protect BRB systems first",
        effects: { resources: { trust: -10 }, tracks: { engineering: 4 }, pressures: { panic: 7 } },
        echoHint: "Hospitals went dark while the prototype stayed online.",
        echoes: [{ type: "ending", hint: "Project-first triage entered the record.", contributor: "brb_grid_first" }],
        tags: ["public_betrayal"],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { capacity: -8, trust: -6 }, pressures: { panic: 6 } },
      echoHint: "The blackout has become evidence of state incapacity.",
      echoes: [{ type: "ending", hint: "Infrastructure neglect entered the record.", contributor: "ignored_blackout" }],
    },
  },
  {
    ...COMMON,
    id: "coalition_vote",
    title: "The Steward Demands a Vote",
    description: "The Steward says coalition partners want authority over the next deposit.",
    type: "advisor",
    weight: 7,
    requirements: { minTrack: { legitimacy: 18 } },
    followUps: [],
    choices: [
      {
        id: "share",
        label: "Share authority",
        effects: { resources: { influence: -5, trust: 8 }, institutions: 7 },
        echoHint: "The coalition now expects shared control at activation.",
        echoes: [{ type: "relationship", hint: "The Steward remembers shared authority.", advisorId: "steward", memory: "shared_activation_authority" }],
      },
      {
        id: "pressure",
        label: "Pressure the holdouts",
        effects: { resources: { influence: -9 }, tracks: { access: 4 }, institutions: -6 },
        echoHint: "The coalition complied, but stopped trusting the process.",
        echoes: [{ type: "ending", hint: "Coerced legitimacy entered the record.", contributor: "coerced_coalition" }],
        tags: ["public_betrayal"],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { influence: -8, trust: -5 } },
      echoHint: "The coalition has begun planning without you.",
      echoes: [{ type: "relationship", hint: "The Steward remembers the unanswered vote.", advisorId: "steward", memory: "ignored_coalition_vote" }],
    },
  },
  {
    ...COMMON,
    id: "corporate_lobby",
    title: "The Corporation Hosts Dinner",
    description: "Key legislators emerge from a private dinner repeating the same talking points.",
    type: "corporation",
    weight: 7,
    requirements: { minTurn: 4 },
    followUps: [],
    choices: [
      {
        id: "expose",
        label: "Expose the guest list",
        effects: { resources: { intelligence: -6, trust: 5 }, corporationProgress: -5 },
        echoHint: "The guest list may support a larger public case.",
        echoes: [{ type: "ending", hint: "Corporate exposure entered the record.", contributor: "exposed_lobby" }],
      },
      {
        id: "outbid",
        label: "Call in your own favors",
        effects: { resources: { influence: -10 }, corporationThreat: -5, advisors: { fixer: { leverage: 3 } } },
        echoHint: "The Fixer now knows the price of your coalition.",
        echoes: [{ type: "relationship", hint: "The Fixer remembers the counter-lobby.", advisorId: "fixer", memory: "ran_counter_lobby" }],
        tags: ["opaque"],
      },
    ],
    ignoredOutcome: {
      effects: { corporationProgress: 6, resources: { influence: -4 } },
      echoHint: "The dinner's agreements are entering committee language.",
      echoes: [{ type: "ending", hint: "Corporate influence entered the record.", contributor: "unchallenged_lobby" }],
    },
  },
  {
    ...RARE,
    id: "emergency_powers",
    title: "The Fixer's Emergency Bill",
    description: "The Fixer offers faster construction through weaker oversight.",
    type: "advisor",
    weight: 4,
    requirements: { minTurn: 8 },
    followUps: [],
    choices: [
      {
        id: "sign",
        label: "Sign it",
        effects: { resources: { capacity: 10, trust: -10 }, institutions: -12, tracks: { engineering: 5 } },
        echoHint: "Emergency authority will outlive this crisis.",
        echoes: [
          { type: "system", hint: "Emergency rule now shapes the campaign.", modifier: "emergency_rule" },
          { type: "ending", hint: "Emergency government entered the record.", contributor: "signed_emergency_powers" },
        ],
        tags: ["opaque", "public_betrayal"],
      },
      {
        id: "veto",
        label: "Preserve normal authority",
        effects: { resources: { influence: -6 }, institutions: 6, pressures: { stress: 5 } },
        echoHint: "The Fixer will remember that you refused the shortcut.",
        echoes: [{ type: "relationship", hint: "The Fixer remembers the veto.", advisorId: "fixer", memory: "emergency_bill_vetoed" }],
      },
    ],
    ignoredOutcome: {
      effects: { pressures: { panic: 8 }, institutions: -5 },
      echoHint: "The emergency expanded while authority remained unclear.",
      echoes: [{ type: "ending", hint: "Indecision under emergency entered the record.", contributor: "emergency_indecision" }],
    },
  },
  {
    ...COMMON,
    id: "capacity_bottleneck",
    title: "Only One Team Can Move",
    description: "Two essential workstreams need the same specialists.",
    type: "crisis",
    weight: 8,
    requirements: { maxResource: { capacity: 30 } },
    followUps: [],
    choices: [
      {
        id: "hire",
        label: "Hire an expensive parallel team",
        effects: { resources: { money: -10, capacity: 9 } },
        echoHint: "A second contractor network now depends on the project.",
        echoes: [{ type: "system", hint: "Parallel contractors changed project capacity.", modifier: "parallel_contractors" }],
      },
      {
        id: "prioritize",
        label: "Prioritize the BRB",
        effects: { tracks: { engineering: 4 }, institutions: -4, pressures: { stress: 4 } },
        echoHint: "Other state work has been formally deprioritized.",
        echoes: [{ type: "ending", hint: "Project priority entered the record.", contributor: "brb_over_services" }],
        tags: ["public_betrayal"],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { capacity: -6 }, tracks: { engineering: -3 } },
      echoHint: "Both teams are now waiting for a decision.",
      echoes: [{ type: "system", hint: "Bottleneck drift changed Engineering.", modifier: "capacity_drift" }],
    },
  },
  {
    ...COMMON,
    id: "audit_discrepancy",
    title: "The Audit Does Not Balance",
    description: "An unexplained payment points toward a hidden Corporation intermediary.",
    type: "corporation",
    weight: 7,
    requirements: { excludedFlags: ["audit_started", "audit_resolved", "audit_closed"] },
    followUps: ["silent_partner"],
    choices: [
      {
        id: "follow",
        label: "Follow the payment",
        effects: { resources: { intelligence: -5 }, pressures: { stress: 2 } },
        echoHint: "A corporate ownership trail has been opened.",
        echoes: [{ type: "card", hint: "A classified follow-up entered the Situation Deck.", addCardIds: ["silent_partner"] }],
        setFlags: ["audit_started"],
        routeChanges: [{ routeId: "corporate_exposure", effect: "open", stepId: "audit_discrepancy" }],
      },
      {
        id: "close",
        label: "Close the audit quietly",
        effects: { resources: { money: 7, trust: -5 }, advisors: { fixer: { leverage: 3 } } },
        echoHint: "The corporate trail has been sealed—for now.",
        echoes: [{ type: "card", hint: "A classified follow-up was removed from the Situation Deck.", removeCardIds: ["silent_partner"] }],
        setFlags: ["audit_closed"],
        routeChanges: [{ routeId: "corporate_exposure", effect: "close", stepId: "audit_discrepancy" }],
        tags: ["opaque"],
      },
    ],
    ignoredOutcome: {
      effects: { corporationProgress: 4 },
      echoHint: "The discrepancy has been normalized as an accounting error.",
      echoes: [{ type: "card", hint: "The ownership trail disappeared from the deck.", removeCardIds: ["silent_partner"] }],
      setFlags: ["audit_closed"],
      routeChanges: [{ routeId: "corporate_exposure", effect: "close", stepId: "audit_discrepancy" }],
    },
  },
  {
    ...RARE,
    id: "silent_partner",
    title: "The Silent Partner",
    description: "The audit reveals Corporation ownership inside a critical contractor.",
    type: "corporation",
    weight: 30,
    requirements: { requiredFlags: ["audit_started"], excludedFlags: ["audit_resolved"] },
    followUps: [],
    choices: [
      {
        id: "seize",
        label: "Seize the contractor",
        effects: { resources: { influence: -8, capacity: -5 }, corporationProgress: -10, institutions: 4 },
        echoHint: "The ownership chain will become part of the public case.",
        echoes: [{ type: "ending", hint: "Corporate exposure entered the final record.", contributor: "corporation_exposed" }],
        setFlags: ["audit_resolved"],
        routeChanges: [{ routeId: "corporate_exposure", effect: "complete", stepId: "silent_partner" }],
      },
      {
        id: "monitor",
        label: "Use it as a controlled channel",
        effects: { resources: { intelligence: 10, trust: -3 }, corporationThreat: 6 },
        echoHint: "The secret channel now implicates your administration too.",
        echoes: [{ type: "ending", hint: "Corporate entanglement entered the final record.", contributor: "corporation_entangled" }],
        setFlags: ["audit_resolved"],
        routeChanges: [{ routeId: "corporate_exposure", effect: "close", stepId: "silent_partner" }],
        tags: ["opaque"],
      },
    ],
    ignoredOutcome: {
      effects: { corporationProgress: 9, corporationThreat: 5 },
      echoHint: "The silent partner has taken operational control.",
      echoes: [{ type: "ending", hint: "Corporate capture entered the final record.", contributor: "silent_partner_ascendant" }],
      setFlags: ["audit_resolved"],
      routeChanges: [{ routeId: "corporate_exposure", effect: "close", stepId: "silent_partner" }],
    },
  },
  {
    ...COMMON,
    id: "protest_spark",
    title: "A Protest at Gate Seven",
    description: "A small group demands to know what the facility will do.",
    type: "crisis",
    weight: 7,
    requirements: {
      minTrack: { legitimacy: 12 },
      excludedFlags: ["protest_started", "protest_resolved"],
    },
    followUps: ["national_march"],
    choices: [
      {
        id: "meet",
        label: "Meet their organizers",
        effects: { resources: { trust: 5 }, pressures: { stress: 2 } },
        echoHint: "The labor leadership will remember this meeting.",
        echoes: [{ type: "card", hint: "A movement follow-up entered the Situation Deck.", addCardIds: ["national_march"] }],
        setFlags: ["protest_started", "protest_met"],
        routeChanges: [{ routeId: "labor_coalition", effect: "open", stepId: "protest_spark" }],
      },
      {
        id: "clear",
        label: "Clear the gate",
        effects: { resources: { capacity: 4, trust: -7 }, pressures: { panic: 4 } },
        echoHint: "Images from Gate Seven are spreading nationally.",
        echoes: [{ type: "card", hint: "A protest follow-up entered the Situation Deck.", addCardIds: ["national_march"] }],
        setFlags: ["protest_started", "protest_cleared"],
        routeChanges: [{ routeId: "labor_coalition", effect: "close", stepId: "protest_spark" }],
        tags: ["public_betrayal"],
      },
    ],
    ignoredOutcome: {
      effects: { resources: { trust: -5 }, pressures: { panic: 4 } },
      echoHint: "The unanswered protest is organizing itself.",
      echoes: [{ type: "card", hint: "A protest follow-up entered the Situation Deck.", addCardIds: ["national_march"] }],
      setFlags: ["protest_started"],
      routeChanges: [{ routeId: "labor_coalition", effect: "close", stepId: "protest_spark" }],
    },
  },
  {
    ...RARE,
    id: "national_march",
    title: "The National March",
    description: "The protest becomes a national test of the project's legitimacy.",
    type: "crisis",
    weight: 30,
    requirements: { requiredFlags: ["protest_started"], excludedFlags: ["protest_resolved"], minTurn: 5 },
    followUps: [],
    choices: [
      {
        id: "address",
        label: "Address the country",
        effects: { resources: { trust: 10, influence: -6 }, pressures: { panic: -5 }, institutions: 6 },
        echoHint: "The movement now expects a place in the BRB settlement.",
        echoes: [{ type: "ending", hint: "A labor-backed settlement entered the final record.", contributor: "labor_backed_activation" }],
        setFlags: ["protest_resolved"],
        routeChanges: [{ routeId: "labor_coalition", effect: "complete", stepId: "national_march" }],
      },
      {
        id: "ban",
        label: "Ban the march",
        effects: { resources: { trust: -12, capacity: 5 }, pressures: { panic: 9 }, institutions: -10 },
        echoHint: "The ban has created a permanent opposition memory.",
        echoes: [{ type: "ending", hint: "Movement suppression entered the final record.", contributor: "march_suppressed" }],
        setFlags: ["protest_resolved"],
        routeChanges: [{ routeId: "labor_coalition", effect: "close", stepId: "national_march" }],
        tags: ["public_betrayal"],
      },
    ],
    ignoredOutcome: {
      effects: { pressures: { panic: 10 }, institutions: -8 },
      echoHint: "The march has become the country's account of your silence.",
      echoes: [{ type: "ending", hint: "Unanswered mobilization entered the final record.", contributor: "march_ignored" }],
      setFlags: ["protest_resolved"],
      routeChanges: [{ routeId: "labor_coalition", effect: "close", stepId: "national_march" }],
    },
  },
];

export const SITUATION_CHAINS = [
  ["audit_discrepancy", "silent_partner"],
  ["protest_spark", "national_march"],
] as const;

export const ROUTE_DEFINITIONS: Record<
  RouteId,
  { label: string; steps: readonly string[]; partialHint: string; classifiedHint: string }
> = {
  labor_coalition: {
    label: "Labor Coalition",
    steps: ["protest_spark", "national_march"],
    partialHint: "Supporting the organizers may have opened a labor-backed path to BRB Stability.",
    classifiedHint: "A coalition route remained unopened. Its first condition is still classified.",
  },
  corporate_exposure: {
    label: "Corporate Exposure",
    steps: ["audit_discrepancy", "silent_partner"],
    partialHint: "Following the ownership trail may have changed who controlled the final activation.",
    classifiedHint: "A corporate ownership route remained hidden in the accounts.",
  },
};

export const FOLLOW_UP_CARD_IDS = new Set(
  SITUATION_CARDS.flatMap((card) => card.followUps),
);
